export type ConceptStage = 'recognise' | 'recall' | 'apply';

export type Concept = {
  id: string;
  unit: 'U1' | 'U2';
  topic: string;
  topicZh: string;
  termEn: string;
  termZh: string;
  definitionEn: string;
  explanationZh: string;
  exampleEn?: string;
  exampleZh?: string;
};

const c = (
  id: string,
  unit: 'U1' | 'U2',
  topic: string,
  topicZh: string,
  termEn: string,
  termZh: string,
  definitionEn: string,
  explanationZh: string,
  exampleEn?: string,
  exampleZh?: string,
): Concept => ({ id, unit, topic, topicZh, termEn, termZh, definitionEn, explanationZh, exampleEn, exampleZh });

export const concepts: Concept[] = [
  // U1 - Introductory concepts
  c('u1-social-science', 'U1', 'intro', '基础概念', 'economics as a social science', '经济学是一门社会科学', 'The study of human economic behaviour using models that cannot usually be tested in controlled experiments.', '经济学研究人的行为，通常无法像自然科学一样进行完全受控实验，因此模型依赖假设。', 'An economist cannot place a whole country in a laboratory.', '经济学家无法把整个国家放进实验室做受控实验。'),
  c('u1-ceteris-paribus', 'U1', 'intro', '基础概念', 'ceteris paribus', '其他条件不变', 'The assumption that all other relevant factors remain unchanged.', '分析一个变量的影响时，假设其他相关因素保持不变。', 'To study the effect of price on demand, income and tastes are held constant.', '研究价格对需求的影响时，收入和偏好保持不变。'),
  c('u1-positive-statement', 'U1', 'intro', '基础概念', 'positive statement', '实证性表述', 'An objective statement that can be tested as true or false.', '实证性表述描述事实，可以用证据检验。', 'A rise in price reduced sales by 10%.', '价格上涨使销量下降了10%。'),
  c('u1-normative-statement', 'U1', 'intro', '基础概念', 'normative statement', '规范性表述', 'A subjective statement based on a value judgement.', '规范性表述包含价值判断，不能只用数据证明。', 'The government should make housing fairer.', '政府应该让住房更加公平。'),
  c('u1-scarcity', 'U1', 'intro', '基础概念', 'scarcity', '稀缺性', 'The problem that finite resources cannot satisfy unlimited wants.', '资源有限而欲望无限，所以必须选择。', 'A town has limited land but many possible uses for it.', '一个城镇土地有限，却有很多不同用途。'),
  c('u1-finite-resource', 'U1', 'intro', '基础概念', 'finite resource', '有限资源', 'A resource that is limited in supply.', '有限资源的可用数量受到限制。', 'The known stock of crude oil is limited.', '已知的原油储量是有限的。'),
  c('u1-renewable-resource', 'U1', 'intro', '基础概念', 'renewable resource', '可再生资源', 'A resource that can regenerate and be used repeatedly.', '可再生资源能够自然恢复并重复使用。', 'Wind and sunlight can be used again and again.', '风能和太阳能可以反复利用。'),
  c('u1-nonrenewable-resource', 'U1', 'intro', '基础概念', 'non-renewable resource', '不可再生资源', 'A resource that cannot be replaced after it is used.', '不可再生资源使用后不能在可预见时期内恢复。', 'Burning oil reduces the remaining stock.', '使用石油会减少剩余储量。'),
  c('u1-opportunity-cost', 'U1', 'intro', '基础概念', 'opportunity cost', '机会成本', 'The next best alternative forgone when a choice is made.', '作出选择时放弃的下一个最佳选择。', 'Building a school means giving up the next best use of the land.', '建学校意味着放弃这块土地的下一个最佳用途。'),
  c('u1-free-good', 'U1', 'intro', '基础概念', 'free good', '自由品', 'A non-scarce good with zero opportunity cost.', '自由品不稀缺，使用它没有机会成本。', 'Ordinary air in an uncrowded place has no price or opportunity cost.', '普通环境中的空气没有价格或机会成本。'),
  c('u1-economic-good', 'U1', 'intro', '基础概念', 'economic good', '经济品', 'A scarce good that has an opportunity cost.', '经济品具有稀缺性，因此存在机会成本。', 'Using steel for cars prevents the same steel being used elsewhere.', '钢材用于汽车后便不能同时用于其他用途。'),
  c('u1-ppf', 'U1', 'intro', '基础概念', 'production possibility frontier', '生产可能性边界', 'The maximum combinations of two goods an economy can produce with current resources and technology.', 'PPF 表示现有资源和技术下两种产品的最大可生产组合。', 'A point on the boundary uses current resources fully.', '边界上的点表示现有资源得到充分利用。'),
  c('u1-ppf-efficient', 'U1', 'intro', '基础概念', 'productive efficiency', '生产效率', 'A situation where output cannot be increased without reducing another output.', '生产有效率时，要增加一种产品就必须减少另一种产品。', 'A point on the PPF is productively efficient.', 'PPF 曲线上的点具有生产效率。'),
  c('u1-ppf-inefficient', 'U1', 'intro', '基础概念', 'attainable but inefficient', '可达到但低效率', 'A point inside the PPF where some resources are unemployed or misused.', 'PPF 内部的点能够达到，但存在闲置或错误配置的资源。', 'Unemployment moves production to a point inside the PPF.', '失业会让经济运行在 PPF 内部。'),
  c('u1-ppf-unattainable', 'U1', 'intro', '基础概念', 'unattainable output', '不可达到的产出', 'A production combination outside the current PPF.', 'PPF 外部的组合超过当前生产能力。', 'A point beyond the current frontier cannot yet be produced.', '当前边界以外的点暂时无法实现。'),
  c('u1-capital-good', 'U1', 'intro', '基础概念', 'capital good', '资本品', 'A good used to produce other goods and services.', '资本品用于生产其他商品或服务。', 'A factory machine helps workers produce more output.', '工厂机器帮助工人生产更多产品。'),
  c('u1-consumer-good', 'U1', 'intro', '基础概念', 'consumer good', '消费品', 'A good or service used directly to satisfy needs and wants.', '消费品直接满足消费者的需要和欲望。', 'A meal bought by a household is consumed directly.', '家庭购买的餐食被直接消费。'),
  c('u1-ppf-growth', 'U1', 'intro', '基础概念', 'outward shift of the PPF', 'PPF 向外移动', 'An increase in an economy’s productive capacity.', '资源、技术或生产率提高会使 PPF 向外移动，表示潜在增长。', 'Better technology allows more of both goods to be produced.', '技术进步使两种产品都能生产得更多。'),
  c('u1-division-labour', 'U1', 'intro', '基础概念', 'division of labour', '劳动分工', 'Breaking production into stages so each worker performs a specific task.', '生产过程被分成不同阶段，每位工人负责特定任务。', 'One worker cuts, another assembles and another packs.', '一名工人切割，另一名组装，还有一名包装。'),
  c('u1-specialisation', 'U1', 'intro', '基础概念', 'specialisation', '专业化', 'Concentrating on a narrow task or range of production.', '个人、企业或国家集中从事较窄范围的任务。', 'A worker repeatedly performs the task at which they are most skilled.', '工人反复完成自己最擅长的任务。'),
  c('u1-money-exchange', 'U1', 'intro', '基础概念', 'medium of exchange', '交换媒介', 'A function of money that allows it to be accepted for buying and selling.', '货币被普遍接受，用来交换商品和服务。', 'A shopper uses money instead of bartering bread for shoes.', '购物者用货币交易，而不是用面包换鞋。'),
  c('u1-money-value', 'U1', 'intro', '基础概念', 'measure of value', '价值尺度', 'A function of money that provides a common unit for comparing prices.', '货币提供共同单位，使不同商品的价值可以比较。', 'Prices in dollars let a buyer compare a phone and a bicycle.', '用同一种货币标价可以比较手机和自行车。'),
  c('u1-money-store', 'U1', 'intro', '基础概念', 'store of value', '价值储存', 'A function of money that carries purchasing power into the future.', '货币能够把购买力保存到未来。', 'Income can be saved today and spent next month.', '今天的收入可以保存到下个月再花。'),
  c('u1-money-deferred', 'U1', 'intro', '基础概念', 'method of deferred payment', '延期付款方式', 'A function of money that allows debts to be stated and paid later.', '货币使借款和未来付款能够明确计价。', 'A buyer receives a product now and repays a loan later.', '消费者现在取得商品，之后再偿还贷款。'),
  c('u1-financial-markets', 'U1', 'intro', '基础概念', 'financial markets', '金融市场', 'Markets that facilitate saving, lending, payments, equities and forward exchange.', '金融市场促进储蓄、借贷、支付、股票和远期交易。', 'Savings are channelled to a business that needs funds to invest.', '储蓄资金被提供给需要投资的企业。'),
  c('u1-free-market', 'U1', 'intro', '基础概念', 'free market economy', '自由市场经济', 'An economy where resources are allocated mainly by demand, supply and the price mechanism.', '自由市场主要通过需求、供给和价格机制配置资源。', 'Profit and prices guide firms with little government intervention.', '企业在较少政府干预下由利润和价格引导。'),
  c('u1-mixed-economy', 'U1', 'intro', '基础概念', 'mixed economy', '混合经济', 'An economy where both markets and government allocate resources.', '混合经济同时依靠市场和政府配置资源。', 'Private shops operate while the state provides street lighting.', '私人商店经营，同时政府提供路灯。'),
  c('u1-command-economy', 'U1', 'intro', '基础概念', 'command economy', '计划经济', 'An economy where the government makes the main resource-allocation decisions.', '计划经济主要由政府决定资源配置。', 'A central authority decides what factories must produce.', '中央机构决定工厂生产什么。'),
  c('u1-rational-choice', 'U1', 'intro', '基础概念', 'rational decision making', '理性决策', 'The assumption that consumers maximise utility and firms maximise profit.', '理性决策假设消费者追求效用最大化，企业追求利润最大化。', 'A consumer compares all costs and benefits before choosing.', '消费者在选择前比较所有成本与收益。'),
  c('u1-behavioural-bias', 'U1', 'intro', '基础概念', 'behavioural bias', '行为偏差', 'A reason such as habit, inertia, framing or social influence that can prevent utility maximisation.', '习惯、惰性、框架效应或从众等因素可能使人无法实现效用最大化。', 'A shopper keeps the same supplier without comparing prices.', '消费者因为习惯而不比较价格，继续使用同一供应商。'),

  // U1 - Demand and supply
  c('u1-demand', 'U1', 'demand-supply', '需求与供给', 'demand', '需求', 'The quantity consumers are willing and able to buy at a given price over a period of time.', '需求必须同时包含愿意购买和有能力购买，并对应特定价格与时期。', 'A person wants a car and has enough income to buy it.', '消费者想买汽车并且有足够收入购买。'),
  c('u1-diminishing-mu', 'U1', 'demand-supply', '需求与供给', 'diminishing marginal utility', '边际效用递减', 'The additional satisfaction from each extra unit consumed gradually falls.', '随着消费量增加，每多消费一单位带来的额外满足感下降。', 'The fifth bottle of water gives less extra satisfaction than the first.', '第五瓶水带来的额外满足感低于第一瓶。'),
  c('u1-extension-demand', 'U1', 'demand-supply', '需求与供给', 'extension in demand', '需求量扩张', 'A rise in quantity demanded caused by a fall in the product’s own price.', '商品自身价格下降会导致沿需求曲线向下移动，需求量扩张。', 'The price falls and buyers purchase more on the same demand curve.', '价格下降后，消费者沿同一需求曲线购买更多。'),
  c('u1-contraction-demand', 'U1', 'demand-supply', '需求与供给', 'contraction in demand', '需求量收缩', 'A fall in quantity demanded caused by a rise in the product’s own price.', '商品自身价格上升会导致沿需求曲线向上移动，需求量收缩。', 'The price rises and buyers purchase less on the same curve.', '价格上涨后，消费者沿同一曲线购买更少。'),
  c('u1-demand-shift', 'U1', 'demand-supply', '需求与供给', 'shift in demand', '需求曲线移动', 'A change in demand at every price caused by a non-price factor.', '收入、偏好、人口、广告或相关商品价格等非价格因素会移动整条需求曲线。', 'Successful advertising raises purchases at every possible price.', '成功广告使每一个价格下的需求都增加。'),
  c('u1-substitute', 'U1', 'demand-supply', '需求与供给', 'substitute good', '替代品', 'A good that can be used in place of another good.', '替代品满足相似需求，消费者可以在两者之间转换。', 'A fall in Nike prices can reduce demand for Adidas.', 'Nike 降价可能减少对 Adidas 的需求。'),
  c('u1-complement', 'U1', 'demand-supply', '需求与供给', 'complementary good', '互补品', 'A good that is consumed jointly with another good.', '互补品通常一起消费。', 'A rise in printer prices may reduce demand for ink cartridges.', '打印机涨价可能减少墨盒需求。'),
  c('u1-supply', 'U1', 'demand-supply', '需求与供给', 'supply', '供给', 'The quantity firms are willing and able to sell at a given price over a period of time.', '供给是企业在特定价格和时期内愿意并且能够出售的数量。', 'A bakery is willing and able to sell 200 loaves at today’s price.', '面包店愿意并能够按今天的价格出售200条面包。'),
  c('u1-extension-supply', 'U1', 'demand-supply', '需求与供给', 'extension in supply', '供给量扩张', 'A rise in quantity supplied caused by a rise in the product’s own price.', '商品自身价格上升会导致沿供给曲线移动，供给量扩张。', 'A higher market price makes firms supply more on the same curve.', '市场价格提高使企业沿同一曲线供给更多。'),
  c('u1-supply-shift', 'U1', 'demand-supply', '需求与供给', 'shift in supply', '供给曲线移动', 'A change in supply at every price caused by a non-price factor.', '生产率、技术、原料成本、补贴或企业数量等因素会移动整条供给曲线。', 'Cheaper raw materials increase supply at every price.', '原材料变便宜使每一个价格下的供给增加。'),

  // U1 - Elasticity
  c('u1-ped', 'U1', 'elasticity', '弹性', 'price elasticity of demand', '需求价格弹性', 'The responsiveness of quantity demanded to a change in price.', 'PED 衡量需求量对价格变化的反应程度。', 'Quantity demanded falls 20% after price rises 10%.', '价格上涨10%后需求量下降20%。'),
  c('u1-ped-formula', 'U1', 'elasticity', '弹性', 'PED formula', 'PED 公式', 'Percentage change in quantity demanded divided by percentage change in price.', 'PED 等于需求量变动百分比除以价格变动百分比。', 'A 30% quantity change divided by a 10% price change gives an absolute PED of 3.', '需求量变动30%除以价格变动10%，PED绝对值为3。'),
  c('u1-elastic-demand', 'U1', 'elasticity', '弹性', 'elastic demand', '富有弹性的需求', 'Demand where quantity changes by a larger percentage than price; absolute PED is greater than one.', '需求量变动百分比大于价格变动百分比，PED绝对值大于1。', 'A 5% price cut causes quantity demanded to rise 15%.', '价格下降5%使需求量增加15%。'),
  c('u1-inelastic-demand', 'U1', 'elasticity', '弹性', 'inelastic demand', '缺乏弹性的需求', 'Demand where quantity changes by a smaller percentage than price; absolute PED is below one.', '需求量变动百分比小于价格变动百分比，PED绝对值小于1。', 'A 10% price rise causes quantity demanded to fall only 2%.', '价格上涨10%只使需求量下降2%。'),
  c('u1-unitary-demand', 'U1', 'elasticity', '弹性', 'unitary elastic demand', '单位弹性需求', 'Demand where the percentage changes in price and quantity are equal; absolute PED is one.', '价格与需求量的百分比变化相等，PED绝对值等于1。', 'Price falls 8% and quantity demanded rises 8%.', '价格下降8%，需求量增加8%。'),
  c('u1-perfect-inelastic', 'U1', 'elasticity', '弹性', 'perfectly inelastic demand', '完全无弹性需求', 'Demand with zero response to price, shown by a vertical demand curve.', '价格变化不会改变需求量，需求曲线竖直，PED等于0。', 'The same quantity is demanded at every price.', '所有价格下需求量都相同。'),
  c('u1-perfect-elastic', 'U1', 'elasticity', '弹性', 'perfectly elastic demand', '完全弹性需求', 'Demand where any price rise reduces quantity demanded to zero, shown by a horizontal curve.', '价格稍微上涨就使需求量降为零，需求曲线水平。', 'Buyers purchase at one price but none at any higher price.', '消费者只接受一个价格，任何更高价格都不购买。'),
  c('u1-total-revenue', 'U1', 'elasticity', '弹性', 'total revenue', '总收益', 'The money received from sales, calculated as price multiplied by quantity.', '总收益等于价格乘以销售数量。', 'A firm sells 50 units at $4 and receives $200.', '企业以4美元销售50件，总收益为200美元。'),
  c('u1-ped-revenue', 'U1', 'elasticity', '弹性', 'PED and total revenue', 'PED 与总收益关系', 'With elastic demand price and revenue move in opposite directions; with inelastic demand they move together.', '需求富有弹性时价格与总收益反向变化；缺乏弹性时同向变化。', 'When demand is elastic, cutting price raises total revenue.', '需求富有弹性时，降价会提高总收益。'),
  c('u1-ped-factors', 'U1', 'elasticity', '弹性', 'determinants of PED', 'PED 的影响因素', 'Substitutes, branding, expenditure share, addictiveness, durability and time influence PED.', '替代品、品牌、支出占比、成瘾性、耐用性与时间会影响PED。', 'A product with many close substitutes usually has more elastic demand.', '拥有许多近似替代品的商品通常需求更富弹性。'),
  c('u1-yed', 'U1', 'elasticity', '弹性', 'income elasticity of demand', '需求收入弹性', 'The responsiveness of quantity demanded to a change in income.', 'YED 衡量需求量对收入变化的反应程度。', 'Income rises 5% and demand for restaurant meals rises 10%.', '收入增加5%，餐厅用餐需求增加10%。'),
  c('u1-normal-good', 'U1', 'elasticity', '弹性', 'normal good', '正常品', 'A good with positive YED whose demand rises when income rises.', '正常品的YED为正，收入增加时需求增加。', 'Households buy more fresh food as income rises.', '收入增加时家庭购买更多新鲜食品。'),
  c('u1-inferior-good', 'U1', 'elasticity', '弹性', 'inferior good', '劣质品', 'A good with negative YED whose demand falls when income rises.', '劣质品的YED为负，收入增加时需求下降。', 'Higher income reduces demand for very cheap instant meals.', '收入提高后，对廉价速食的需求下降。'),
  c('u1-luxury-good', 'U1', 'elasticity', '弹性', 'luxury good', '奢侈品', 'A normal good with YED greater than one.', '奢侈品的需求对收入变化反应较大，YED大于1。', 'Demand for overseas holidays rises faster than income.', '海外旅行需求增长快于收入增长。'),
  c('u1-xed', 'U1', 'elasticity', '弹性', 'cross elasticity of demand', '交叉需求弹性', 'The responsiveness of demand for one good to a change in the price of another good.', 'XED 衡量一种商品需求量对另一种商品价格变化的反应。', 'Coffee prices rise and demand for tea changes.', '咖啡价格上涨后，茶的需求发生变化。'),
  c('u1-pes', 'U1', 'elasticity', '弹性', 'price elasticity of supply', '供给价格弹性', 'The responsiveness of quantity supplied to a change in price.', 'PES 衡量供给量对价格变化的反应程度。', 'Price rises 10% and firms increase output 5%.', '价格上涨10%，企业把产量提高5%。'),
  c('u1-pes-factors', 'U1', 'elasticity', '弹性', 'determinants of PES', 'PES 的影响因素', 'Time, stocks, perishability, factor mobility, spare capacity and legal constraints influence PES.', '时间、库存、易腐性、要素流动性、剩余产能与法律限制会影响PES。', 'Supply becomes more elastic when firms have spare capacity and stocks.', '企业拥有剩余产能和库存时，供给更富弹性。'),
  c('u1-short-long-run', 'U1', 'elasticity', '弹性', 'short run and long run', '短期与长期', 'In the short run some factors are fixed; in the long run all factors can vary.', '短期内部分生产要素固定，长期内所有要素都可以调整。', 'A firm cannot build a new factory immediately but can do so over time.', '企业不能立刻建新工厂，但长期可以。'),

  // U1 - Equilibrium and price mechanism
  c('u1-equilibrium', 'U1', 'equilibrium', '市场均衡', 'market equilibrium', '市场均衡', 'The price and quantity where quantity demanded equals quantity supplied.', '需求量等于供给量时形成市场均衡。', 'At the clearing price there is neither a shortage nor a surplus.', '市场出清价格下既没有短缺也没有过剩。'),
  c('u1-excess-demand', 'U1', 'equilibrium', '市场均衡', 'excess demand', '超额需求', 'A shortage where quantity demanded exceeds quantity supplied.', '需求量大于供给量时出现短缺，价格受到向上压力。', 'A price below equilibrium attracts more buyers than sellers.', '低于均衡的价格使需求量超过供给量。'),
  c('u1-excess-supply', 'U1', 'equilibrium', '市场均衡', 'excess supply', '超额供给', 'A surplus where quantity supplied exceeds quantity demanded.', '供给量大于需求量时出现过剩，价格受到向下压力。', 'A price above equilibrium leaves unsold stock.', '高于均衡的价格造成未售出的库存。'),
  c('u1-consumer-surplus', 'U1', 'equilibrium', '市场均衡', 'consumer surplus', '消费者剩余', 'The difference between willingness to pay and the price actually paid.', '消费者愿意支付的价格减去实际支付价格。', 'A buyer willing to pay $10 pays only $7 and gains $3 surplus.', '消费者愿付10美元但只付7美元，获得3美元剩余。'),
  c('u1-producer-surplus', 'U1', 'equilibrium', '市场均衡', 'producer surplus', '生产者剩余', 'The difference between the price received and the minimum price a producer would accept.', '生产者实际收到的价格减去愿意接受的最低价格。', 'A seller willing to accept $4 receives $6.', '卖方最低愿收4美元，实际收到6美元。'),
  c('u1-price-rationing', 'U1', 'equilibrium', '市场均衡', 'rationing function', '价格的配给功能', 'Rising prices allocate scarce goods to consumers willing and able to pay.', '价格上涨把稀缺商品分配给愿意且有能力支付的人。', 'A shortage raises price until fewer buyers remain.', '短缺使价格上升，直到部分买家退出。'),
  c('u1-price-incentive', 'U1', 'equilibrium', '市场均衡', 'incentive function', '价格的激励功能', 'Higher prices and profit encourage firms to increase production.', '更高价格和利润激励企业扩大生产。', 'Rising coffee prices encourage farmers to grow more coffee.', '咖啡价格上涨激励农民种植更多咖啡。'),
  c('u1-price-signalling', 'U1', 'equilibrium', '市场均衡', 'signalling function', '价格的信号功能', 'Price changes communicate information about scarcity and market conditions.', '价格变化向消费者和生产者传递稀缺程度与市场状况。', 'A rising price signals that demand may be high relative to supply.', '价格上涨传递需求相对供给较高的信号。'),

  // U1 - Intervention
  c('u1-indirect-tax', 'U1', 'intervention', '税、补贴与政府干预', 'indirect tax', '间接税', 'A tax on spending or production that raises firms’ costs and reduces supply.', '间接税对支出或生产征收，通常提高成本并减少供给。', 'A tax on cigarettes shifts the supply curve left.', '香烟税使供给曲线左移。'),
  c('u1-ad-valorem-tax', 'U1', 'intervention', '税、补贴与政府干预', 'ad valorem tax', '从价税', 'A tax charged as a percentage of the value or price of a product.', '从价税按商品价值或价格的一定比例征收。', 'A 10% sales tax becomes larger when the product price rises.', '10%的销售税会随商品价格上升而增加。'),
  c('u1-specific-tax', 'U1', 'intervention', '税、补贴与政府干预', 'specific tax', '从量税', 'A fixed tax amount charged per unit regardless of the product price.', '从量税对每单位商品征收固定金额。', 'A $2 tax is charged on every packet sold.', '每售出一包都征收2美元税。'),
  c('u1-tax-incidence', 'U1', 'intervention', '税、补贴与政府干预', 'tax incidence', '税负归宿', 'The division of a tax burden between consumers and producers.', '税负归宿描述税收负担由消费者和生产者分别承担多少。', 'Inelastic demand allows firms to pass more of a tax to consumers.', '需求缺乏弹性时，企业更容易把税负转嫁给消费者。'),
  c('u1-subsidy', 'U1', 'intervention', '税、补贴与政府干预', 'subsidy', '补贴', 'A government payment that lowers production costs and encourages output.', '补贴是政府付款，用于降低成本并鼓励生产。', 'A payment for solar panels shifts supply right and lowers price.', '太阳能板补贴使供给右移并降低价格。'),
  c('u1-maximum-price', 'U1', 'intervention', '税、补贴与政府干预', 'maximum price', '最高限价', 'A legal price ceiling set below equilibrium to keep a good affordable.', '有效最高限价设置在均衡价格以下，通常造成短缺。', 'Rent control below equilibrium creates excess demand for housing.', '低于均衡的租金上限造成住房超额需求。'),
  c('u1-minimum-price', 'U1', 'intervention', '税、补贴与政府干预', 'minimum price', '最低限价', 'A legal price floor set above equilibrium.', '有效最低限价设置在均衡价格以上，通常造成过剩。', 'A guaranteed farm price creates excess supply that may be stored.', '农产品保证价格造成过剩，政府可能需要储存。'),
  c('u1-tradable-permits', 'U1', 'intervention', '税、补贴与政府干预', 'tradable pollution permits', '可交易污染许可证', 'Permits that allow a limited amount of pollution and can be bought or sold.', '政府限制污染总量并允许企业交易排放许可。', 'A low-polluting firm sells unused permits for profit.', '低污染企业出售未使用的许可证获利。'),
  c('u1-regulation', 'U1', 'intervention', '税、补贴与政府干预', 'regulation', '管制', 'Rules backed by penalties that limit production, sale or use.', '政府通过规则、罚款或其他处罚限制生产、销售或使用。', 'A legal emissions limit is enforced with fines.', '政府用罚款执行法定排放上限。'),
  c('u1-information-provision', 'U1', 'intervention', '税、补贴与政府干预', 'provision of information', '信息提供', 'Government information intended to correct information gaps.', '政府向消费者提供信息，以纠正信息缺口。', 'Nutrition labels help buyers understand health effects.', '营养标签帮助消费者了解健康影响。'),
  c('u1-state-provision', 'U1', 'intervention', '税、补贴与政府干预', 'state provision', '政府直接提供', 'Government production or funding of goods that markets underprovide.', '政府直接生产或资助市场供给不足的商品与服务。', 'Tax revenue funds street lighting.', '税收收入用于提供路灯。'),
  c('u1-intervention-evaluation', 'U1', 'intervention', '税、补贴与政府干预', 'evaluation of intervention', '政府干预评价', 'Assessment using magnitude, time, elasticity, measurement, opportunity cost and different groups.', '评价政策要考虑影响大小、时间、弹性、测量、机会成本和不同群体。', 'A tax may be ineffective when demand is highly inelastic.', '需求非常缺乏弹性时，税收可能效果有限。'),

  // U1 - Market failure and government failure
  c('u1-market-failure', 'U1', 'market-failure', '市场失灵', 'market failure', '市场失灵', 'An inefficient allocation of resources by the market mechanism.', '市场机制导致资源低效率配置，社会福利没有最大化。', 'A polluting factory produces beyond the socially optimal output.', '污染企业的产量超过社会最优水平。'),
  c('u1-private-benefit', 'U1', 'market-failure', '市场失灵', 'private benefit', '私人成本收益中的私人收益', 'A benefit received directly by a participant in a transaction.', '私人收益由交易的直接参与者获得。', 'A student gains higher future income from education.', '学生从教育中获得更高的未来收入。'),
  c('u1-external-benefit', 'U1', 'market-failure', '市场失灵', 'external benefit', '外部收益', 'A benefit received by a third party outside a transaction.', '外部收益由交易之外的第三方获得。', 'Vaccination reduces infection risk for other people.', '接种疫苗降低他人的感染风险。'),
  c('u1-social-benefit', 'U1', 'market-failure', '市场失灵', 'social benefit', '社会收益', 'The total of private benefit and external benefit.', '社会收益等于私人收益加外部收益。', 'The full benefit of education includes the student’s gain and wider social gains.', '教育的全部收益包括学生私人收益和更广泛的社会收益。'),
  c('u1-private-cost', 'U1', 'market-failure', '市场失灵', 'private cost', '私人成本', 'A cost paid directly by a participant in a transaction.', '私人成本由交易的直接参与者承担。', 'A factory pays wages and electricity bills.', '工厂支付工资和电费。'),
  c('u1-external-cost', 'U1', 'market-failure', '市场失灵', 'external cost', '外部成本', 'A cost imposed on a third party outside a transaction.', '外部成本由没有参与交易的第三方承担。', 'Nearby residents suffer from factory air pollution.', '附近居民承受工厂空气污染。'),
  c('u1-social-cost', 'U1', 'market-failure', '市场失灵', 'social cost', '社会成本', 'The total of private cost and external cost.', '社会成本等于私人成本加外部成本。', 'The full cost of driving includes fuel and congestion imposed on others.', '开车的全部成本包括燃料费和对他人造成的拥堵。'),
  c('u1-negative-externality', 'U1', 'market-failure', '市场失灵', 'negative externality', '负外部性', 'A harmful effect on a third party from production or consumption.', '生产或消费给第三方带来未计入价格的损害。', 'Second-hand smoke harms people outside the transaction.', '二手烟伤害交易之外的人。'),
  c('u1-positive-externality', 'U1', 'market-failure', '市场失灵', 'positive externality', '正外部性', 'A beneficial effect on a third party from production or consumption.', '生产或消费给第三方带来未计入价格的收益。', 'Education can raise productivity and reduce crime for society.', '教育可以提高社会生产率并减少犯罪。'),
  c('u1-welfare-loss', 'U1', 'market-failure', '市场失灵', 'welfare loss', '福利损失', 'The loss of total social surplus when output differs from the social optimum.', '实际产量偏离社会最优产量时会损失社会总福利。', 'Ignoring pollution causes overproduction and a triangular welfare loss.', '忽略污染会导致过度生产和三角形福利损失。'),
  c('u1-public-good', 'U1', 'market-failure', '市场失灵', 'public good', '公共品', 'A good that is both non-rival and non-excludable.', '公共品同时具有非竞争性和非排他性。', 'One person using street lighting does not prevent others using it.', '一个人使用路灯不会妨碍其他人使用。'),
  c('u1-non-rival', 'U1', 'market-failure', '市场失灵', 'non-rival', '非竞争性', 'One person’s consumption does not reduce availability for others.', '一个人的消费不会减少其他人可使用的数量。', 'Many ships can use the same lighthouse signal.', '许多船只可以同时使用同一灯塔信号。'),
  c('u1-non-excludable', 'U1', 'market-failure', '市场失灵', 'non-excludable', '非排他性', 'It is difficult or impossible to prevent non-payers from consuming a good.', '很难或无法阻止未付款者使用该商品。', 'People cannot easily be excluded from national defence.', '很难把未付款者排除在国防保护之外。'),
  c('u1-free-rider', 'U1', 'market-failure', '市场失灵', 'free-rider problem', '搭便车问题', 'People benefit without paying, reducing the incentive for private provision.', '人们不付费也能受益，使私人企业缺乏供给动力。', 'A household enjoys street lighting without paying the provider directly.', '家庭没有直接付款也能享受路灯。'),
  c('u1-imperfect-information', 'U1', 'market-failure', '市场失灵', 'imperfect information', '不完全信息', 'A situation where economic agents do not have all relevant information.', '经济主体没有掌握所有相关信息。', 'A buyer does not know the long-term health effects of a product.', '消费者不知道产品的长期健康影响。'),
  c('u1-asymmetric-information', 'U1', 'market-failure', '市场失灵', 'asymmetric information', '信息不对称', 'A situation where one side of a transaction has more information than the other.', '交易一方掌握的信息多于另一方。', 'A used-car seller knows more about faults than the buyer.', '二手车卖家比买家更了解车辆故障。'),
  c('u1-information-gap', 'U1', 'market-failure', '市场失灵', 'information gap', '信息缺口', 'Missing knowledge that can cause irrational decisions and misallocation.', '缺失的信息可能导致非理性决策和资源错误配置。', 'Consumers underuse education because they underestimate its benefits.', '消费者低估教育收益，从而消费不足。'),
  c('u1-moral-hazard', 'U1', 'market-failure', '市场失灵', 'moral hazard', '道德风险', 'Taking greater risks because another party is expected to bear the cost.', '因为预计别人承担损失而采取更多风险。', 'Full insurance may reduce a person’s incentive to take precautions.', '完全保险可能降低个人采取预防措施的动力。'),
  c('u1-speculation', 'U1', 'market-failure', '市场失灵', 'speculation', '投机', 'Buying or selling in expectation of a future price change to make profit.', '为了从未来价格变化中获利而买卖资产。', 'Investors buy houses only because they expect prices to rise.', '投资者只因预期房价上涨而买房。'),
  c('u1-market-bubble', 'U1', 'market-failure', '市场失灵', 'market bubble', '市场泡沫', 'A self-reinforcing rise in demand that pushes price beyond a sustainable level.', '需求相互强化，把价格推到难以持续的水平。', 'House prices rise mainly because buyers expect further rises.', '买家因为预期继续上涨而买房，推动房价脱离基本面。'),
  c('u1-government-failure', 'U1', 'market-failure', '市场失灵', 'government failure', '政府失灵', 'Government intervention that causes a less efficient allocation and net welfare loss.', '政府干预反而使资源配置更低效并造成净福利损失。', 'A badly designed subsidy creates more costs than benefits.', '设计不当的补贴造成的成本超过收益。'),
  c('u1-government-failure-causes', 'U1', 'market-failure', '市场失灵', 'causes of government failure', '政府失灵原因', 'Information gaps, distorted price signals, unintended effects, administration costs and conflicting objectives.', '政府失灵可能来自信息缺口、价格信号失真、意外后果、行政成本和目标冲突。', 'A policy is based on inaccurate data and produces an unintended shortage.', '政策依据错误数据并意外造成短缺。'),

  // U2 - Economic growth
  c('u2-gdp', 'U2', 'growth', '经济增长', 'gross domestic product', '国内生产总值', 'The value of final goods and services produced within an economy in a year.', 'GDP衡量一国境内一年内生产的最终商品和服务价值。', 'The value of final output produced inside Singapore is counted.', '在新加坡境内生产的最终产出计入其GDP。'),
  c('u2-real-gdp', 'U2', 'growth', '经济增长', 'real GDP', '实际 GDP', 'GDP adjusted for changes in the average price level.', '实际GDP扣除了通货膨胀的影响，更能反映真实产量。', 'Nominal output rises 6% while prices rise 4%, so real growth is about 2%.', '名义产出增长6%、物价增长4%，实际增长约2%。'),
  c('u2-nominal-gdp', 'U2', 'growth', '经济增长', 'nominal GDP', '名义 GDP', 'GDP measured at current prices without adjusting for inflation.', '名义GDP按当期价格计算，没有扣除通胀。', 'Money GDP rises only because prices increase.', 'GDP金额只因为价格上涨而增加。'),
  c('u2-gni', 'U2', 'growth', '经济增长', 'gross national income', '国民总收入', 'GDP plus net overseas factor income such as interest, profit and dividends.', 'GNI等于GDP加来自海外的净要素收入。', 'Profits earned abroad by domestic residents are added to GDP in GNI.', '本国居民在海外赚取的利润计入GNI。'),
  c('u2-real-gdp-capita', 'U2', 'growth', '经济增长', 'real GDP per capita', '人均实际 GDP', 'Real GDP divided by population.', '人均实际GDP等于实际GDP除以人口，更适合比较平均生活水平。', 'Real GDP grows 2% but population grows 3%, so real GDP per person falls.', '实际GDP增长2%而人口增长3%，人均实际GDP下降。'),
  c('u2-ppp', 'U2', 'growth', '经济增长', 'purchasing power parity', '购买力平价', 'An exchange rate that compares the cost of a similar basket of goods across countries.', '购买力平价根据相同商品篮子的成本比较不同货币购买力。', 'Market exchange rates may understate how much local income can buy.', '市场汇率可能低估当地收入实际能买到的商品。'),
  c('u2-recession', 'U2', 'growth', '经济增长', 'recession', '经济衰退', 'Two consecutive quarters of negative real GDP growth.', '常见技术定义是实际GDP连续两个季度负增长。', 'Real GDP falls in both quarter one and quarter two.', '实际GDP在第一和第二季度都下降。'),
  c('u2-gdp-limitations', 'U2', 'growth', '经济增长', 'limitations of GDP', 'GDP 的局限', 'GDP does not fully show distribution, quality of life, environment, unpaid work or composition of output.', 'GDP不能完整反映收入分配、生活质量、环境、无偿劳动和产出结构。', 'Average GDP rises while most income gains go to a small group.', '平均GDP上升，但大部分收入增长只归少数人。'),
  c('u2-income-happiness', 'U2', 'growth', '经济增长', 'income and happiness', '收入与幸福感', 'Life satisfaction tends to rise with income but at a diminishing rate after basic needs are met.', '收入提高通常增加幸福感，但满足基本需要后边际提升会下降。', 'Another $1,000 matters less to a rich household than to a poor one.', '额外1000美元对富裕家庭的幸福提升小于贫困家庭。'),

  // U2 - Inflation
  c('u2-inflation', 'U2', 'inflation', '通货膨胀', 'inflation', '通货膨胀', 'A sustained increase in the average price level.', '通货膨胀是总体价格水平持续上升。', 'Prices across the economy rise repeatedly, not just one product once.', '整体物价持续上涨，而不是单个商品一次涨价。'),
  c('u2-deflation', 'U2', 'inflation', '通货膨胀', 'deflation', '通货紧缩', 'A sustained fall in the average price level.', '通货紧缩是总体价格水平持续下降。', 'The CPI level falls from one year to the next.', 'CPI指数水平比上一年下降。'),
  c('u2-disinflation', 'U2', 'inflation', '通货膨胀', 'disinflation', '通胀率下降', 'A fall in the positive rate of inflation; prices still rise more slowly.', '反通胀是正的通胀率下降，价格仍上涨但速度变慢。', 'Inflation falls from 5% to 2%.', '通胀率从5%下降到2%。'),
  c('u2-cpi', 'U2', 'inflation', '通货膨胀', 'consumer price index', '消费物价指数', 'A weighted measure of changes in the price of a representative basket of consumer goods and services.', 'CPI按代表性消费篮子及支出权重衡量价格变化。', 'Housing receives a larger weight than pencils in a typical household basket.', '住房在典型家庭消费篮子中的权重大于铅笔。'),
  c('u2-cpi-process', 'U2', 'inflation', '通货膨胀', 'CPI calculation process', 'CPI 计算过程', 'Choose a base year and basket, collect prices, apply expenditure weights and calculate a weighted index.', 'CPI需要选择基年和商品篮子、采集价格、应用支出权重并计算加权指数。', 'Prices are sampled from many retail outlets and compared with a base year.', '从许多零售点采价并与基年比较。'),
  c('u2-cpi-limitations', 'U2', 'inflation', '通货膨胀', 'limitations of CPI', 'CPI 的局限', 'The basket may not represent every household and consumption patterns and product quality change.', 'CPI商品篮子不一定代表所有家庭，消费习惯和产品质量也会改变。', 'A pensioner and a student have very different spending patterns.', '退休者和学生的支出结构很不相同。'),
  c('u2-ppi', 'U2', 'inflation', '通货膨胀', 'producer price index', '生产者价格指数', 'An index of firms’ input or wholesale costs that can signal future consumer inflation.', '生产者价格指数反映企业投入或批发成本，可能预示未来CPI变化。', 'Rising wholesale energy costs may later raise shop prices.', '批发能源成本上涨可能随后推高零售价格。'),
  c('u2-demand-pull', 'U2', 'inflation', '通货膨胀', 'demand-pull inflation', '需求拉动型通胀', 'Inflation caused by aggregate demand growing faster than productive capacity.', '总需求增长快于生产能力会造成需求拉动型通胀。', 'Strong consumer spending shifts AD right near full capacity.', '经济接近充分产能时消费强劲，使AD右移。'),
  c('u2-cost-push', 'U2', 'inflation', '通货膨胀', 'cost-push inflation', '成本推动型通胀', 'Inflation caused by rising production costs and a leftward shift of SRAS.', '生产成本上升使SRAS左移，造成成本推动型通胀。', 'A sharp oil price increase raises firms’ costs.', '石油价格大涨提高企业成本。'),
  c('u2-money-inflation', 'U2', 'inflation', '通货膨胀', 'excessive money supply growth', '货币供应量过度增长', 'Inflationary pressure caused when money growth persistently exceeds output growth.', '货币供应量长期增长快于产出，会增加通胀压力。', 'Too much money chases too few goods.', '过多货币追逐过少商品。'),
  c('u2-inflation-costs', 'U2', 'inflation', '通货膨胀', 'costs of high inflation', '高通胀的成本', 'High inflation creates uncertainty, reduces competitiveness, redistributes income and raises menu and shoe-leather costs.', '高通胀带来不确定性、竞争力下降、收入再分配及菜单成本等。', 'Firms delay investment because future costs and demand are uncertain.', '企业因未来成本和需求不确定而推迟投资。'),
  c('u2-deflation-effects', 'U2', 'inflation', '通货膨胀', 'effects of deflation', '通缩的影响', 'Falling prices can delay spending, raise real debt burdens and increase unemployment.', '价格下降可能使消费推迟、实际债务负担上升并增加失业。', 'Consumers wait for lower future prices, reducing current AD.', '消费者等待未来更低价格，减少当前总需求。'),
  c('u2-stable-inflation', 'U2', 'inflation', '通货膨胀', 'low and stable inflation', '低而稳定的通胀', 'Predictable modest inflation that supports planning and avoids the costs of deflation.', '低而稳定的通胀便于家庭与企业规划，并降低通缩风险。', 'Firms can make long-term contracts with less uncertainty.', '企业能够在较低不确定性下签订长期合同。'),

  // U2 - Unemployment
  c('u2-ilo-unemployment', 'U2', 'unemployment', '失业', 'ILO unemployment', 'ILO 失业定义', 'People without work who are available within two weeks and have actively sought work recently.', 'ILO失业者没有工作、两周内可以工作，并且最近积极寻找工作。', 'A person applied for jobs last week and can start tomorrow.', '某人上周申请工作并且明天可以上班。'),
  c('u2-unemployment-rate', 'U2', 'unemployment', '失业', 'unemployment rate', '失业率', 'ILO unemployed divided by the economically active population, multiplied by 100.', '失业率等于ILO失业人数除以经济活动人口再乘100。', '50 unemployed people in a labour force of 1,000 gives 5%.', '劳动力1000人中50人失业，失业率为5%。'),
  c('u2-underemployment', 'U2', 'unemployment', '失业', 'underemployment', '就业不足', 'Working fewer hours than desired or in a job that does not fully use a person’s skills.', '劳动者工作时间不足，或岗位没有充分利用其技能。', 'A trained engineer can only find a few hours of low-skilled work.', '受过训练的工程师只能找到少量低技能工作。'),
  c('u2-frictional', 'U2', 'unemployment', '失业', 'frictional unemployment', '摩擦性失业', 'Short-term unemployment while people move between jobs.', '劳动者在转换工作过程中产生的短期失业。', 'A graduate searches for a suitable first job.', '毕业生正在寻找合适的第一份工作。'),
  c('u2-seasonal', 'U2', 'unemployment', '失业', 'seasonal unemployment', '季节性失业', 'Unemployment caused by predictable seasonal changes in demand.', '需求随季节规律变化造成的失业。', 'A ski resort needs fewer workers in summer.', '滑雪场在夏季需要较少员工。'),
  c('u2-structural', 'U2', 'unemployment', '失业', 'structural unemployment', '结构性失业', 'Unemployment caused by a mismatch between workers’ skills or location and available jobs.', '劳动者技能或地点与现有岗位不匹配造成的失业。', 'Coal workers lack the skills needed by growing technology firms.', '煤矿工人的技能不符合增长中的科技企业需求。'),
  c('u2-cyclical', 'U2', 'unemployment', '失业', 'cyclical unemployment', '周期性失业', 'Unemployment caused by insufficient aggregate demand during a downturn.', '经济衰退时总需求不足造成的失业。', 'Restaurants dismiss staff after household spending falls in a recession.', '衰退中家庭支出下降，餐厅裁员。'),
  c('u2-economic-inactive', 'U2', 'unemployment', '失业', 'economically inactive', '经济非活跃人口', 'Working-age people who are not employed and are not actively seeking work.', '适龄人口中没有工作且没有积极寻找工作的人。', 'A full-time student not looking for a job is outside the labour force.', '没有找工作的全日制学生不属于劳动力。'),
  c('u2-net-migration', 'U2', 'unemployment', '失业', 'net migration', '净移民', 'Immigration minus emigration, which can affect labour supply, demand and unemployment.', '净移民等于移入减移出，会同时影响劳动力供给、消费需求和失业。', 'New migrants increase labour supply but also spend income in the economy.', '新移民增加劳动力供给，也会在经济中消费。'),

  // U2 - Balance of payments
  c('u2-bop', 'U2', 'bop', '国际收支', 'balance of payments', '国际收支', 'A record of a country’s economic transactions with the rest of the world.', '国际收支记录一国与世界其他地区之间的经济交易。', 'It includes current, capital and financial accounts.', '它包括经常账户、资本账户和金融账户。'),
  c('u2-current-account', 'U2', 'bop', '国际收支', 'current account', '经常账户', 'A record of trade in goods and services, income flows and current transfers.', '经常账户记录商品和服务贸易、收入流和经常转移。', 'Export revenue and remittances are recorded here.', '出口收入和汇款记录在经常账户。'),
  c('u2-visible-balance', 'U2', 'bop', '国际收支', 'visible trade balance', '有形贸易余额', 'Revenue from goods exports minus expenditure on goods imports.', '有形贸易余额等于商品出口收入减商品进口支出。', 'Car exports are compared with food imports.', '汽车出口与食品进口的金额相比较。'),
  c('u2-invisible-balance', 'U2', 'bop', '国际收支', 'invisible balance', '无形贸易余额', 'Net trade in services plus income flows and current transfers.', '无形余额包括服务贸易、收入流和经常转移的净额。', 'Tourism services, dividends and foreign aid are included.', '旅游服务、股息和外国援助包括在内。'),
  c('u2-current-surplus', 'U2', 'bop', '国际收支', 'current account surplus', '经常账户顺差', 'A positive current account balance where inflows exceed outflows.', '经常账户流入超过流出时形成顺差。', 'Export and income receipts exceed import and transfer payments.', '出口和收入所得超过进口及转移支出。'),
  c('u2-depreciation-bop', 'U2', 'bop', '国际收支', 'currency depreciation', '货币贬值', 'A fall in a currency’s value that makes exports cheaper and imports dearer, ceteris paribus.', '本币贬值通常使出口对外国人更便宜、进口对本国人更昂贵。', 'Foreign buyers need less of their currency to buy domestic exports.', '外国买家购买本国出口所需本币成本下降。'),

  // U2 - Aggregate demand and supply
  c('u2-ad', 'U2', 'ad-as', '总需求与总供给', 'aggregate demand', '总需求', 'Total planned expenditure on domestic output at a given price level.', '总需求是在给定价格水平下对本国产出的计划总支出。', 'AD equals consumption, investment, government spending and net exports.', 'AD由消费、投资、政府支出和净出口组成。'),
  c('u2-ad-formula', 'U2', 'ad-as', '总需求与总供给', 'AD = C + I + G + (X - M)', '总需求公式', 'The formula combining consumption, investment, government expenditure and net trade.', '总需求等于消费、投资、政府支出加净出口。', 'A rise in imports reduces AD, ceteris paribus.', '其他条件不变时，进口增加会降低AD。'),
  c('u2-consumption', 'U2', 'ad-as', '总需求与总供给', 'consumption', '消费', 'Household spending on goods and services.', '消费是家庭对商品和服务的支出。', 'Households buy food, transport and entertainment.', '家庭购买食品、交通和娱乐服务。'),
  c('u2-saving-ratio', 'U2', 'ad-as', '总需求与总供给', 'saving ratio', '储蓄率', 'The percentage of disposable income that households save.', '储蓄率是家庭储蓄占可支配收入的比例。', 'Higher interest rates may encourage a higher saving ratio.', '利率上升可能鼓励更高储蓄率。'),
  c('u2-investment', 'U2', 'ad-as', '总需求与总供给', 'investment', '投资', 'Spending that increases the economy’s capital stock.', '投资是增加资本存量的支出。', 'A firm buys a new machine and builds a factory.', '企业购买新机器并建造工厂。'),
  c('u2-gross-net-investment', 'U2', 'ad-as', '总需求与总供给', 'net investment', '净投资', 'Gross investment minus depreciation of existing capital.', '净投资等于总投资减去现有资本折旧。', 'Investment of 100 with depreciation of 30 gives net investment of 70.', '总投资100、折旧30，净投资为70。'),
  c('u2-investment-factors', 'U2', 'ad-as', '总需求与总供给', 'determinants of investment', '投资的影响因素', 'Growth, interest rates, confidence, credit availability and business taxes influence investment.', '经济增长、利率、信心、信贷和企业税影响投资。', 'Lower interest rates and stronger confidence encourage firms to invest.', '低利率和更强信心鼓励企业投资。'),
  c('u2-government-expenditure', 'U2', 'ad-as', '总需求与总供给', 'government expenditure', '政府支出', 'Public-sector spending on goods, services and investment.', '政府支出是公共部门对商品、服务和投资的支出。', 'The government builds hospitals and pays teachers.', '政府建设医院并支付教师工资。'),
  c('u2-net-trade', 'U2', 'ad-as', '总需求与总供给', 'net trade', '净贸易', 'Exports minus imports.', '净贸易等于出口减进口。', 'Exports of 80 and imports of 60 give net trade of 20.', '出口80、进口60，净贸易为20。'),
  c('u2-as', 'U2', 'ad-as', '总需求与总供给', 'aggregate supply', '总供给', 'The total output firms are willing to produce at a given price level.', '总供给是在给定价格水平下企业愿意生产的总产出。', 'Higher economy-wide prices may encourage more short-run output.', '整体价格提高可能鼓励更多短期产出。'),
  c('u2-sras', 'U2', 'ad-as', '总需求与总供给', 'short-run aggregate supply', '短期总供给', 'Aggregate supply when some input prices and productive capacity are fixed.', '短期内部分投入价格和生产能力固定，SRAS通常向右上方倾斜。', 'Higher wage or energy costs shift SRAS left.', '工资或能源成本提高使SRAS左移。'),
  c('u2-sras-factors', 'U2', 'ad-as', '总需求与总供给', 'determinants of SRAS', 'SRAS 的影响因素', 'Wages, raw materials, taxes, subsidies, exchange rates and productivity shift SRAS.', '工资、原料、税收、补贴、汇率和生产率会移动SRAS。', 'A subsidy lowers costs and shifts SRAS right.', '补贴降低成本，使SRAS右移。'),
  c('u2-lras', 'U2', 'ad-as', '总需求与总供给', 'long-run aggregate supply', '长期总供给', 'The economy’s productive capacity when all factor adjustments are possible.', 'LRAS表示所有生产要素都能调整时的潜在生产能力。', 'More capital and better skills shift LRAS right.', '更多资本和更好技能使LRAS右移。'),
  c('u2-classical-lras', 'U2', 'ad-as', '总需求与总供给', 'classical LRAS', '古典 LRAS', 'A vertical long-run supply curve at full-capacity output.', '古典LRAS在充分产能处竖直，长期产出由供给能力决定。', 'An AD increase changes price but not long-run real output at full capacity.', '充分产能下AD增加只改变长期价格，不改变实际产出。'),
  c('u2-keynesian-lras', 'U2', 'ad-as', '总需求与总供给', 'Keynesian LRAS', '凯恩斯 LRAS', 'A curve that is flat with spare capacity and becomes vertical near full capacity.', '凯恩斯LRAS在闲置产能较多时较平坦，接近充分产能时变为竖直。', 'Extra demand raises output easily in recession but mostly raises prices near capacity.', '衰退时需求增加主要提高产出，接近产能时主要推高价格。'),
  c('u2-ad-as-equilibrium', 'U2', 'ad-as', '总需求与总供给', 'macroeconomic equilibrium', '宏观经济均衡', 'The price level and real output where aggregate demand equals aggregate supply.', 'AD与AS相交决定均衡价格水平和实际产出。', 'The intersection of AD and SRAS gives short-run equilibrium.', 'AD与SRAS交点给出短期均衡。'),

  // U2 - National income, multiplier and growth
  c('u2-circular-flow', 'U2', 'national-income', '国民收入与乘数', 'circular flow of income', '收入循环流动', 'Flows of goods, services and corresponding money payments between households and firms.', '家庭和企业之间存在商品服务流与相对应的货币支付流。', 'Households supply labour and receive income, then spend on firms’ output.', '家庭提供劳动获得收入，再购买企业产出。'),
  c('u2-income', 'U2', 'national-income', '国民收入与乘数', 'income', '收入', 'A flow of disposable resources received over a period of time.', '收入是在一段时期内获得、可用于消费或储蓄的流量。', 'A worker receives wages each month.', '劳动者每月获得工资。'),
  c('u2-wealth', 'U2', 'national-income', '国民收入与乘数', 'wealth', '财富', 'The value of assets owned minus liabilities owed at a point in time.', '财富是某一时点资产价值减去负债。', 'A household’s home and savings minus its mortgage are net wealth.', '家庭住房和储蓄减去房贷构成净财富。'),
  c('u2-injection', 'U2', 'national-income', '国民收入与乘数', 'injection', '注入', 'An inflow into the circular flow: investment, government spending or exports.', '投资、政府支出和出口是收入循环中的注入。', 'Foreign demand for exports adds spending to the domestic circular flow.', '国外对出口的需求把支出注入国内循环。'),
  c('u2-withdrawal', 'U2', 'national-income', '国民收入与乘数', 'withdrawal', '漏出', 'An outflow from the circular flow: saving, taxation or imports.', '储蓄、税收和进口是收入循环中的漏出。', 'Spending on imports leaves the domestic circular flow.', '进口支出流出国内收入循环。'),
  c('u2-multiplier', 'U2', 'national-income', '国民收入与乘数', 'multiplier', '乘数', 'The process by which an initial change in AD causes a larger final change in national income.', '初始总需求变化通过多轮收入和支出产生更大的最终国民收入变化。', 'An initial $10m investment eventually raises income by $40m.', '初始1000万美元投资最终使收入增加4000万美元。'),
  c('u2-mpc', 'U2', 'national-income', '国民收入与乘数', 'marginal propensity to consume', '边际消费倾向', 'The proportion of extra income that is spent on consumption.', 'MPC是新增收入中用于消费的比例；MPC越大，乘数越大。', 'From an extra $100 income, $80 is spent, so MPC is 0.8.', '新增100美元收入中消费80美元，MPC为0.8。'),
  c('u2-mps', 'U2', 'national-income', '国民收入与乘数', 'marginal propensity to save', '边际储蓄倾向', 'The proportion of extra income that is saved.', 'MPS是新增收入中用于储蓄的比例；MPS越大，乘数越小。', 'From an extra $100, $20 is saved, so MPS is 0.2.', '新增100美元收入中储蓄20美元，MPS为0.2。'),
  c('u2-mpw', 'U2', 'national-income', '国民收入与乘数', 'marginal propensity to withdraw', '边际漏出倾向', 'MPS plus MPT plus MPM; the share of extra income leaving domestic consumption.', 'MPW等于MPS、MPT和MPM之和，表示新增收入中的总漏出比例。', 'More saving, tax and imports reduce the multiplier.', '更多储蓄、税收和进口会缩小乘数。'),
  c('u2-actual-growth', 'U2', 'national-income', '国民收入与乘数', 'actual economic growth', '实际经济增长', 'An increase in current real GDP, often caused by higher aggregate demand.', '实际增长是当前实际GDP增加，常由总需求上升推动。', 'Unused factories raise production after AD increases.', 'AD增加后，闲置工厂提高生产。'),
  c('u2-potential-growth', 'U2', 'national-income', '国民收入与乘数', 'potential economic growth', '潜在经济增长', 'An increase in the economy’s maximum productive capacity.', '潜在增长是经济最大生产能力提高，表现为LRAS或PPF向外移动。', 'Education and new capital allow more sustainable output.', '教育与新资本提高可持续产出。'),
  c('u2-output-gap', 'U2', 'national-income', '国民收入与乘数', 'output gap', '产出缺口', 'The difference between actual real output and potential output.', '产出缺口是实际产出与潜在产出之间的差额。', 'Actual GDP below capacity creates spare resources.', '实际GDP低于产能时存在闲置资源。'),
  c('u2-negative-gap', 'U2', 'national-income', '国民收入与乘数', 'negative output gap', '负产出缺口', 'Actual output below potential output, usually with spare capacity and cyclical unemployment.', '实际产出低于潜在产出，通常伴随闲置产能和周期性失业。', 'A recession leaves factories and workers idle.', '衰退使工厂和工人闲置。'),
  c('u2-positive-gap', 'U2', 'national-income', '国民收入与乘数', 'positive output gap', '正产出缺口', 'Actual output temporarily above sustainable potential, creating inflationary pressure.', '实际产出暂时超过可持续潜在产出，形成通胀压力。', 'Overtime and intense capacity use push output beyond its trend.', '加班和高强度使用产能使产出暂时超过趋势水平。'),
  c('u2-growth-cost-benefit', 'U2', 'national-income', '国民收入与乘数', 'costs and benefits of growth', '经济增长的成本与收益', 'Growth may raise income, jobs and tax revenue but can cause inflation, inequality, resource depletion and pollution.', '增长提高收入、就业和税收，但也可能带来通胀、不平等、资源消耗和污染。', 'Higher output reduces unemployment but increases carbon emissions.', '更高产出降低失业，却增加碳排放。'),

  // U2 - Macro objectives and policies
  c('u2-macro-objectives', 'U2', 'policy', '宏观政策', 'macroeconomic objectives', '宏观经济目标', 'Growth, low stable inflation, low unemployment, current-account balance, budget balance and greater equality.', '宏观目标包括增长、低而稳定的通胀、低失业、经常账户平衡、预算平衡和更公平收入。', 'A government targets 2% inflation and low unemployment.', '政府设定2%通胀目标并追求低失业。'),
  c('u2-objective-conflict', 'U2', 'policy', '宏观政策', 'conflict between objectives', '宏观目标冲突', 'Improving one macro objective can make another worse.', '改善一个宏观目标可能使另一个目标恶化。', 'Reducing inflation by cutting AD may increase unemployment.', '通过减少AD降低通胀可能提高失业。'),
  c('u2-phillips-curve', 'U2', 'policy', '宏观政策', 'short-run Phillips curve', '短期菲利普斯曲线', 'An inverse short-run relationship between inflation and unemployment.', '短期菲利普斯曲线表示通胀与失业之间的反向关系。', 'Lower unemployment may be associated with higher demand-pull inflation.', '较低失业可能伴随更高的需求拉动型通胀。'),
  c('u2-supply-side', 'U2', 'policy', '宏观政策', 'supply-side policy', '供给侧政策', 'Policies designed to increase productivity and long-run aggregate supply.', '供给侧政策旨在提高生产率和长期总供给。', 'Training and infrastructure shift LRAS right.', '培训和基础设施建设使LRAS右移。'),
  c('u2-market-supply-policy', 'U2', 'policy', '宏观政策', 'market-oriented supply-side policy', '市场导向供给侧政策', 'Policies such as lower direct taxes, deregulation, privatisation and labour-market reform.', '市场导向政策包括降低直接税、放松管制、私有化和劳动力市场改革。', 'Lower corporation tax aims to strengthen incentives to invest.', '降低公司税旨在增强投资激励。'),
  c('u2-intervention-supply-policy', 'U2', 'policy', '宏观政策', 'interventionist supply-side policy', '干预型供给侧政策', 'Government spending on education, research and infrastructure to raise productive capacity.', '政府通过教育、研发和基础设施支出提高生产能力。', 'Publicly funded training raises human capital.', '政府资助培训提高人力资本。'),
  c('u2-fiscal-policy', 'U2', 'policy', '宏观政策', 'fiscal policy', '财政政策', 'The use of taxation, government spending and borrowing to influence aggregate demand.', '财政政策通过税收、政府支出和借款影响总需求。', 'The government cuts income tax to raise consumption.', '政府降低所得税以刺激消费。'),
  c('u2-monetary-policy', 'U2', 'policy', '宏观政策', 'monetary policy', '货币政策', 'The use of interest rates, money and quantitative easing to influence aggregate demand.', '货币政策通过利率、货币供应和量化宽松影响总需求。', 'The central bank lowers its policy interest rate.', '中央银行降低政策利率。'),
  c('u2-reflationary-policy', 'U2', 'policy', '宏观政策', 'reflationary policy', '扩张性政策', 'Fiscal or monetary action intended to raise aggregate demand and economic activity.', '扩张性政策提高总需求和经济活动。', 'Higher government spending shifts AD right.', '政府支出增加使AD右移。'),
  c('u2-deflationary-policy', 'U2', 'policy', '宏观政策', 'deflationary policy', '紧缩性政策', 'Fiscal or monetary action intended to reduce aggregate demand and inflationary pressure.', '紧缩性政策降低总需求和通胀压力。', 'Higher taxes or interest rates shift AD left.', '提高税收或利率使AD左移。'),
  c('u2-quantitative-easing', 'U2', 'policy', '宏观政策', 'quantitative easing', '量化宽松', 'Central-bank purchases of financial assets using newly created money to lower yields and stimulate spending.', '央行用新创造的货币购买金融资产，以降低收益率并刺激支出。', 'The central bank buys government bonds from financial institutions.', '央行从金融机构购买政府债券。'),
  c('u2-base-rate', 'U2', 'policy', '宏观政策', 'base interest rate', '基准利率', 'The interest rate charged by the central bank when lending to commercial banks.', '基准利率是中央银行向商业银行贷款时使用的重要政策利率。', 'A higher base rate raises borrowing costs and encourages saving.', '基准利率提高会增加借贷成本并鼓励储蓄。'),
  c('u2-central-bank', 'U2', 'policy', '宏观政策', 'central bank', '中央银行', 'The institution that implements monetary policy, targets inflation, serves banks and acts as lender of last resort.', '中央银行执行货币政策、实现通胀目标、服务银行并充当最后贷款人。', 'It lends emergency funds to a solvent bank facing a liquidity shortage.', '它向面临流动性短缺但仍有偿付能力的银行提供紧急资金。'),
  c('u2-policy-evaluation', 'U2', 'policy', '宏观政策', 'policy evaluation', '宏观政策评价', 'Assessment of time lags, confidence, size, trade-offs, opportunity cost and unintended effects.', '评价政策要考虑时间滞后、信心、规模、目标冲突、机会成本和意外影响。', 'Low confidence may make an interest-rate cut ineffective.', '消费者和企业信心低时，降息可能效果有限。'),
];

export const conceptCountByUnit = {
  U1: concepts.filter((concept) => concept.unit === 'U1').length,
  U2: concepts.filter((concept) => concept.unit === 'U2').length,
};
